// src/vue/components/Example.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Plus } from 'lucide-vue-next'

const count = ref(0)
</script>

<template>
  <div :class="$style.root">
    count is {{ count }}
    <button type="button" @click="count++"><Plus /></button>
  </div>
</template>

<style module>
.root {
  color: #888;
}
</style>

// src/react/components/Example.tsx
import { useState } from 'react'
import style from './Example.module.css'
import { Plus } from 'lucide-react'

export function Example() {
  const [count, setCount] = useState(0)
  return (
    <div className={style.root}>
      count is {count}
      <button onClick={() => setCount((count) => count + 1)}>
        <Plus />
      </button>
    </div>
  )
}
